# Generated by Django 3.1.7 on 2021-04-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListFiltered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('priority', models.CharField(max_length=10)),
                ('readiness', models.BooleanField()),
                ('todolist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filtered_note', to='todolistapp.todolist')),
            ],
        ),
    ]
